[tool.poetry]
authors     = ["Taras Ivashchuk <taras@tarasivashchuk.com>"]
description = "Algorithmic trading using deep learning"
name        = "marketml"
version     = "0.1.0"

        [tool.poetry.dependencies]
        backtrader        = "*"
        logzero           = "*"
        pandas            = "*"
        pandas_datareader = "*"
        python            = "^3.8"
        tqdm              = "*"
        yahoo_fin         = "*"

        [tool.poetry.dev-dependencies]

[tool.black]
line-length = 100

[build-system]
build-backend = "poetry.masonry.api"
requires      = ["poetry>=0.12"]
