[tool.poetry]
name = "marketml"
version = "0.1.0"
description = "Algorithmic trading using deep learning"
authors = ["Taras Ivashchuk <taras@tarasivashchuk.com>"]

[tool.poetry.dependencies]
python = "^3.8"
logzero = "*"
tqdm = "*"
uvloop = "*"
aiohttp = "*"
aiostream = "*"
numpy = "*"
pandas = "*"
pandas_datareader = "*"
yahoo_fin = "*"
backtrader = "^1.9.75"

[tool.poetry.dev-dependencies]
pytest = "*"
mypy = "*"
flake8 = "*"
black = {version="*", allow-prereleases=true}
isort = "*"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
